<?php
echo "<HTML>\r\n<!-- Lotus-Domino (Release 5.0.5 - September 22, 2000 on Windows NT/Intel) -->\r\n<HEAD>\r\n<TITLE>过法国df -Word,Office强制痕迹保留web文档控件,手写签名,电子盖章(电子印章、电子签章),支持全部菜单,打印预览.Domino安全,集成,开发,创建OA系统的利器！</TITLE><meta http-equiv=\"content-type\" content=\"text/html;charset=gb2312\">";
echo "<S";
echo "CRIPT LANGUAGE=\"JavaScript\"  type=\"text/javascript\" src=\"/admin/ocv14_test.nsf/date.js\"></SCRIPT>";
echo "<S";
echo "CRIPT LANGUAGE=\"JavaScript\"  type=\"text/javascript\" src=\"/admin/ocv14_test.nsf/VWOCX/tangerocx.js/\$file/tangerocx.js\"></SCRIPT>";
echo "<S";
echo "CRIPT LANGUAGE=\"JavaScript\"  type=\"text/javascript\" src=\"/admin/ocv14_test.nsf/VWOCX/word.js/\$file/word.js\"></SCRIPT><link rel=\"stylesheet\" type=\"text/css\" href=\"/admin/ocv14_test.nsf/css.css\">\r\n";
echo "<S";
echo "CRIPT LANGUAGE=\"JavaScript\">\r\n<!-- \r\ndocument._domino_target = \"_self\";\r\nfunction _doClick(v, o, t) {\r\n  var url=\"/admin/ocv14_test.nsf/vwAllDocsByUNID/436cdd26d80a84b4482571b6000a74de?OpenDocument&Click=\" + v;\r\n  if (o.href != null)\r\n    o.href = url;\r\n  else {\r\n    if (t == null)\r\n      t = document._domino_target;\r\n    window.open(url, t);\r\n  }\r\n\r\n}\r\n// -->\r\n</SCRIPT>\r\n</HEAD>\r\n<BODY TEXT=\"000000\" ";
echo "BGCOLOR=\"FFFFFF\" onload=\"addMyMenuItems();TANGER_OCX_Init('/admin/ocv14_test.nsf/vwOCX/default.doc/\$FILE/default.doc');\">\r\n\r\n<FORM><B><FONT SIZE=5>Word文档</FONT></B>";
echo "<s";
echo "tyle>\r\nbutton.op{\r\nwidth:90px;\r\nbackground-color:#9DC2DB;\r\nborder:1px #EEEEEE solid;\r\ncursor: hand;\r\n}\r\nbutton.op1{\r\nbackground-color:#9DC2DB;\r\nborder:1px #EEEEEE solid;\r\ncursor: hand;\r\n}\r\n.opinfo{\r\ncolor:red;\r\n}\r\n</style>\r\n<HR>\r\n<center><table width=80% border=0 cellpadding=0 cellspacing=0>\r\n\t<tr>\r\n             <td align=\"center\"><button class=\"op1\" onclick=\"document.URL='436CDD26D80A84B4482571B6000A74D";
echo "E?editdocument'\">编辑文档</button></td>\r\n\t\t<td width=\"10\"  ></td>\r\n              <td align=\"center\"><button class=\"op1\" onclick=\"window.close()\" >关闭窗口</button></td>\r\n\t\t<td width=\"10\" ></td>\r\n\t</tr>\r\n</table></center><br>\r\n<FIELDSET><LEGEND>以下是将要和在线编辑文档同时一次性提交的其他信息（采用我们独创的“智能提交”技术）</LEGEND>\r\n<TABLE width=100% BORDER=0 CELLSPACING=0 CELLPADDING=0>\r\n<TR VALIGN=top><TD width=5";
echo "0% WIDTH=\"348\" VALIGN=middle>文件标题：&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE=2>过法国df</FONT></TD><TD WIDTH=\"406\" ROWSPAN=2 VALIGN=middle>文件类别：(可多选)&nbsp;<FONT SIZE=2></FONT></TD></TR>\r\n\r\n<TR VALIGN=top><TD width=500 WIDTH=\"348\" VALIGN=middle>发布日期：&nbsp;&nbsp;&nbsp;&nbsp;dsafsdads\r\n</TD></TR>\r\n\r\n<TR VALIGN=top><TD WIDTH=\"348\" VALIGN=middle>流转方向：&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE=2>发文</FONT></TD><T";
echo "D WIDTH=\"406\" ROWSPAN=2 VALIGN=middle>文件等级：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE=2>普通</FONT></TD></TR>\r\n\r\n<TR VALIGN=top><TD WIDTH=\"348\" VALIGN=middle>流转目标：&nbsp;&nbsp;&nbsp;&nbsp;<FONT SIZE=2></FONT></TD></TR>\r\n\r\n<TR VALIGN=top><TD WIDTH=\"754\" COLSPAN=2 VALIGN=middle>备　　注：&nbsp;&nbsp;&nbsp;&nbsp;dddd</TD></TR>\r\n</TABLE>\r\n<br><FIELDSET style=\"width:700px\"><LEGEND>以下是该";
echo "文档中的其他附件:（如果在编辑状态，选择的附件将被删除）</LEGEND>\r\n<FONT SIZE=2>　</FONT></FIELDSET>\r\n</FIELDSET>\r\n<table width=100% height=700 border=1 cellpadding=0 cellspacing=0 style=\"border:1px #9dc2db solid\">\r\n<tr height=26><td colspan=2><font color=\"red\"><b>提示：本示例程序仅演示了控件的部分功能.通过操作菜单或者Javascript可以进行更多控制.详细功能请参考编程手册.</b></font></td></tr>\r\n<tr height=26><td colspa";
echo "n=2><font color=\"red\">提示：本地印章需要使用专门的印章制作工具，请到http://www.ntko.com的免费下载处下载.</font></td></tr>\r\n<tr height=26><td colspan=2><font color=\"red\">提示：所有远程印章(财务章，合同章，行政章)的口令是8个1：11111111</font></td></tr>\r\n<tr height=26 width=100%>\r\n<td class=\"opinfo\" width=90>文档相关操作:</td>\r\n<td width=100%>\r\n<BUTTON class=\"op1\" onclick=\"TANGER_OCX_SetDocUser(document.all('TANGER";
echo "_OCX_CurrentUser').value);\">设置演示用户</button>\r\n<INPUT id=\"TANGER_OCX_CurrentUser\" type=text size=8 VALUE=\"用户30\">\r\n</td></tr>\r\n<tr width=100%>\r\n<td valign=top width=90>\r\n";
echo "<s";
echo "pan class=\"opinfo\" onclick=\"\">[打印控制]</span>\r\n<button class=\"op\" onclick=\"TANGER_OCX_PrintDoc(true)\">后台打印</button>\r\n<button class=\"op\" onclick=\"TANGER_OCX_PrintDoc(false)\">前台打印</button>\r\n<button class=\"op\" onclick=\"TANGER_OCX_OBJ.FilePrint=false;\">禁止打印</button>\r\n<button class=\"op\" onclick=\"TANGER_OCX_OBJ.FilePrint=true;\">允许打印</button>\r\n</td>\r\n<td valign=\"top\">\r\n<!-- 当前操作-->";
echo "<S";
echo "PAN ID=\"TANGER_OCX_op\" style=\"display:none\">3</SPAN>\r\n<!-- 附件文件名,在附件提交之前设定-->";
echo "<S";
echo "PAN style=\"display:none\"><FONT SIZE=2 COLOR=\"0000FF\"> </FONT><FONT SIZE=2 COLOR=\"0000ff\">newdoc.doc</FONT><FONT SIZE=2 COLOR=\"0000FF\"> </FONT></SPAN>\r\n<!-- 已有附件文件名-->";
echo "<S";
echo "PAN ID=\"TANGER_OCX_attachName\" style=\"display:none\">newdoc.doc</SPAN>\r\n<!-- 已有附件url-->";
echo "<S";
echo "PAN ID=\"TANGER_OCX_attachURL\" style=\"display:none\">436CDD26D80A84B4482571B6000A74DE/\$File/newdoc.doc</SPAN><!-- 加密印章的key-->";
echo "<S";
echo "PAN ID=\"TANGER_OCX_key\" style=\"display:none\">WWWW-6S245T</SPAN>\r\n";
echo "<s";
echo "cript src=\"/admin/ocv14_test.nsf/pgNtkoGenObjJsForRead\"></script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=\"TANGER_OCX\" event=\"OnSignSelect(issign,signinfo)\">\r\n\tif(issign)\r\n\t{\r\n\t\tdocument.all(\"signmes\").innerHTML = signinfo;\r\n\t\t//var cuser = document.all('TANGER_OCX_Username').value;\r\n\t\tif(signinfo.indexOf(TANGER_OCX_Username) == -1)\r\n\t\t{\r\n\t\t\tTANGER_OCX_OBJ.SetReadOnly(true);\r\n\t\t\tTANGER_OCX_OBJ.SetReadOnly(false);\r\n\t\t}\r\n\t}\r\n\telse\r\n\t{\r\n\t\tdocument.all(\"signmes\").innerHTML = \"";
echo "是图片，或者不是合法印章\";\r\n\t}\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=\"TANGER_OCX\" event=\"AfterCheckSign()\">\r\n\t//TANGER_OCX_OBJ.SetReadOnly(true,\"\",1);//打开此注释可在检查签名之后保护印章\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=\"TANGER_OCX\" event=\"AfterHandSignOrDraw(DrawOrSign,canceled)\">\r\n\t//TANGER_OCX_OBJ.SetReadOnly(true,\"\",1);//打开此注释可在增加印章或者签名之后保护印章\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=\"TANGER_OCX\" event=\"OnCustomMenuCmd(menuIndex,menuCaption,menuID)\">\r\nalert(\"第\" + menuIndex +\"个菜单项,menuID=\"+menuID+\",菜单标题为\\\"\"+menuCaption+\"\\\"的命令被执行.\");\r\nswitch(menuID)\r\n{\r\n   case 1:\r\n       try{\r\n   \tTANGER_OCX_OBJ.IsNoCopy = !TANGER_OCX_OBJ.IsNoCopy;\r\n\tif(TANGER_OCX_OBJ.IsNoCopy)\r\n\t{\r\n\t  alert(\"禁止拷贝和拖放功能已经打开。此时将不允许拷贝内容和拖放文字";
echo "。\");\r\n\t}\r\n\telse\r\n\t{\r\n\t  alert(\"禁止拷贝和拖放功能已经关闭。此时将允许拷贝内容和拖放文字。\");\r\n\t}\r\n      }catch(e){};\r\n      break;\r\n   case 2:\r\n       alert(\"此菜单命令仅显示此信息。\");\r\n      break;\r\n   default:\r\n      alert(\"此菜单命令未处理。\");\r\n      break;\r\n}\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=\"TANGER_OCX\" event=\"OnCustomFileMenuCmd(menuIndex,menuCaption,menuID)\">\r\nalert(\"第\" + menuIndex +\"个菜单项,menuID=\"+menuID+\",菜单标题为\\\"\"+menuCaption+\"\\\"的命令被执行.\");\r\nswitch(menuID)\r\n{\r\ncase 1:\r\nbreak;\r\ndefault:\r\nalert(\"此命令显示此信息！\");\r\nbreak;\r\n}\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=TANGER_OCX event=\"OnDocumentClosed()\">\r\nTANGER_OCX_OnDocumentClosed()\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\">\r\nvar TANGER_OCX_str;\r\nvar TANGER_OCX_obj;\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=TANGER_OCX event=\"OnDocumentOpened(TANGER_OCX_str,TANGER_OCX_obj)\">\r\nTANGER_OCX_OnDocumentOpened(TANGER_OCX_str,TANGER_OCX_obj)\r\n</script>\r\n";
echo "<s";
echo "cript language=\"JScript\" for=\"TANGER_OCX\" event=\"AfterOpenFromURL(doc)\">\r\n\tTANGER_OCX_SetDocUser(document.all('TANGER_OCX_CurrentUser').value);\r\n\tswitch(TANGER_OCX_strOp)\r\n\t{\r\n\t\tcase \"1\":\r\n\t\tcase \"2\":\t\t\t\t    \r\n\t\t\tTANGER_OCX_OBJ.SetReadOnly(false);\r\n\t\t\t//TANGER_OCX_SetMarkModify(true);\r\n\t\t\tbreak;\r\n\t\tcase \"3\":\r\n\t\t\tTANGER_OCX_OBJ.SetReadOnly(true);\r\n\t\t\tbreak;\r\n\t\tdefault:\r\n\t\t\tTANGER_OCX_SetMarkModify(";
echo "true);\r\n\t\t\tbreak;\r\n\t}\r\n</script>\r\n</td>\r\n</tr></table>\r\n<center>\r\n<table width=100% height=120 border=0 CELLPADDING=0 CELLSPACING=0 bgcolor=\"#dedfde\"><TR><TD class=\"copyright\" valign=\"middle\" align=\"center\">\r\n官方网站: <a class=\"leftareadoc\" href=\"HTTP://WWW.NTKO.COM\">HTTP://WWW.NTKO.COM</A><BR>\r\n千航网络[NTKO SOFTWARE]版权所有2003-2006,保留所有权利.<BR>电子邮件:<a class=\"leftareadoc\" href=\"mailto:sale@ntko.co";
echo "m\">SALE@NTKO.COM</A>&nbsp;<a class=\"leftareadoc\" href=\"mailto:ntko2k@126.com\">NTKO2K@126.COM</A><BR>联系电话:023-62929797&nbsp;&nbsp;13896158802 <BR>联系人:刘先生\r\n</TD></TR></table>\r\n</center>\r\n</FORM>\r\n</BODY>\r\n</HTML>\r\n";
?>
