<?php
@session_start( );
include( $Htmledit_Path."/../includes/db.inc.php" );
include( $Htmledit_Path."/../includes/config.php" );
if ( $Htmledit_Tag == "Htmledit" )
{
    $ImgPath = "http://".$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];
    $ImgPath = str_replace( "sliblook_commerce.php", "images/", $ImgPath );
}
else
{
    exit( );
}
echo "<HTML><HEAD><TITLE>选择图片</TITLE>\r\n<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\r\n</HEAD>\r\n<BODY leftMargin=0 topMargin=0 marginheight=\"0\" marginwidth=\"0\" bgcolor=\"#666666\">\r\n<table width=\"545\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" align=\"center\">\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0001.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0001.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0001.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0002.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0002.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0002.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0003.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0003.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0003.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0004.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0004.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0004.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0005.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0005.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0005.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0006.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0006.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0006.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0007.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0007.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0007.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0008.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0008.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0008.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0009.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0009.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0009.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0010.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0010.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0010.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0011.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0011.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0011.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0012.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0012.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0012.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0013.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0013.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0013.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0014.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0014.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0014.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0015.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0015.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0015.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0016.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0016.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0016.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0017.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0017.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0017.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0018.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0018.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0018.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0019.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0019.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0019.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0020.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0020.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0020.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0021.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0021.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0021.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0022.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0022.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0022.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0023.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0023.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0023.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0024.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0024.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0024.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0025.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0025.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0025.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0026.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0026.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0026.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "0027.jpg width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0027.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "0027.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n</td>\r\n<td height=136 width=108>\r\n</td>\r\n<td height=136 width=108>\r\n</td>\r\n</tr>\r\n</table>\r\n</BODY></HTML>\r\n";
?>
