<?php
@session_start( );
include( $Htmledit_Path."/../includes/db.inc.php" );
include( $Htmledit_Path."/../includes/config.php" );
if ( $Htmledit_Tag == "Htmledit" )
{
    $ImgPath = "http://".$_SERVER['HTTP_HOST'].$_SERVER['PHP_SELF'];
    $ImgPath = str_replace( "sliblook_trade.php", "images/", $ImgPath );
}
else
{
    exit( );
}
echo "<HTML><HEAD><TITLE>选择图片</TITLE>\r\n<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\r\n</HEAD>\r\n<BODY leftMargin=0 topMargin=0 marginheight=\"0\" marginwidth=\"0\" bgcolor=\"#666666\">\r\n<table width=\"545\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\" align=\"center\">\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "019.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "019.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "019.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "020.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "020.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "020.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "021.gif width=\"100\" height=\"92\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "021.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "021.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "022.gif width=\"68\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "022.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "022.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "023.gif width=\"98\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "023.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "023.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "024.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "024.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "024.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "025.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "025.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "025.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "026.gif width=\"96\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "026.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "026.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "027.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "027.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "027.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "028.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "028.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "028.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "029.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "029.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "029.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "030.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "030.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "030.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "031.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "031.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "031.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "032.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "032.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "032.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "033.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "033.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "033.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "034.gif width=\"100\" height=\"89\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "034.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "034.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "035.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "035.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "035.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "036.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "036.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "036.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "037.gif width=\"100\" height=\"99\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "037.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "037.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "038.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "038.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "038.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "039.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "039.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "039.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "040.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "040.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "040.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "041.gif width=\"94\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "041.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "041.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "042.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "042.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "042.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "56.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "56.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "56.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "d.gif width=\"88\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "d.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "d.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Hein013.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Hein013.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Hein013.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Hein031.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Hein031.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Hein031.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Hein22.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Hein22.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Hein22.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "HeinH04.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "HeinH04.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "HeinH04.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "home_pic1.jpg width=\"66\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "home_pic1.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "home_pic1.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "home_pic2.jpg width=\"66\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "home_pic2.jpg'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "home_pic2.jpg'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Internet.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Internet.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Internet.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Osx22.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Osx22.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Osx22.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "rt6.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "rt6.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "rt6.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "ruh.gif width=\"84\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "ruh.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "ruh.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "sdf.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "sdf.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "sdf.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "SwedishMailbox.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "SwedishMailbox.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "SwedishMailbox.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Tokimeki13.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Tokimeki13.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Tokimeki13.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Tokimeki8.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Tokimeki8.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Tokimeki8.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n</tr>\r\n<tr bgcolor=\"#FFFFFF\" align=\"center\">\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Woa11.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Woa11.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Woa11.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Woa30.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Woa30.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Woa30.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Xbutton51.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Xbutton51.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Xbutton51.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n<table width=100% height=128 border=0 cellspacing=0 cellpadding=0 align=center>\r\n<tr><td align=center height=108>\r\n<img src=";
echo $ImgPath;
echo "Xmas18.gif width=\"100\" height=\"100\" onDblClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Xmas18.gif'\">\r\n</td></tr><tr><td height=28 bgcolor=#d4d0c8 align=center>\r\n<INPUT onClick=\"window.location='sliblook.php?step=ok&nowfile=";
echo $ImgPath;
echo "Xmas18.gif'\" type=button value=选中>\r\n</td></tr></table>\r\n</td>\r\n<td height=136 width=108>\r\n</td>\r\n</tr>\r\n</table>\r\n</BODY></HTML>\r\n";
?>
