<?php
@session_start( );
include( $Htmledit_Path."/../includes/db.inc.php" );
include( $Htmledit_Path."/../includes/config.php" );
if ( $Htmledit_Tag != "Htmledit" )
{
    exit( );
}
echo "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n<title>选择图片</title>\r\n<link href=\"../css/pop.css\" type=\"text/css\" rel=\"stylesheet\">\r\n</head>\r\n\r\n<body bgcolor=\"menu\">\r\n<table cellSpacing=0 cellPadding=5 width=\"100%\">\r\n    <tr> \r\n      <td><FIELDSET><LEGEND>图片库</LEGEND><br>\r\n        <table width=\"717\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" bordercolorlight=\"#999999\" bordercolordark=\"#FFFFFF\">\r\n          <tr> \r\n            <td width=\"149\" height=\"30\" align=\"center\" background=\"images/btbg.gif\"><a href=\"sliblook.php\" target=\"look\"><font color=\"#000000\">我的图片</font></a></td>\r\n            <td valign=\"top\" rowspan=\"5\" bgcolor=\"#666666\"><iframe src='sliblook.php' name='look' height='100%' width='100%' scrolling='yes' marginheight='0' frameborder='0'></iframe></td>\r\n          </tr>\r\n          <tr> \r\n            <td width=\"149\" height=\"30\" align=\"center\" background=\"images/btbg.gif\"><a href=\"sliblook_commerce.php\" target=\"look\"><font color=\"#000000\">商务图库</font></a></td>\r\n          </tr>\r\n          <tr> \r\n            <td width=\"149\" height=\"30\" align=\"center\" background=\"images/btbg.gif\"><a href=\"sliblook_trade.php\" target=\"look\"><font color=\"#000000\">行业图库</font></a></td>\r\n          </tr>\r\n          <tr> \r\n            <td width=\"149\" height=\"30\" align=\"center\" background=\"images/btbg.gif\"><a href=\"sliblook_icon.php\" target=\"look\"><font color=\"#000000\">小 图 标</font></a></td>\r\n          </tr>\r\n          <tr> \r\n            <td width=\"149\" height=\"157\" valign=\"top\" background=\"images/btbg.gif\">&nbsp;</td>\r\n          </tr>\r\n        </table>\r\n        </FIELDSET></td>\r\n    </tr>\r\n  <tr>\r\n      <td align=right> \r\n        <table width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"0\">\r\n          <tr>\r\n            <!--td width=\"86%\">\r\n              <div align=\"center\">您的媒体目录空间是30720k &nbsp;&nbsp;现已使用8k &nbsp;&nbsp;可用空间30712k</div>\r\n            </td-->\r\n            <td width=\"14%\" align=\"right\"> \r\n              <input onClick=\"javascript: window.close();\" type=button value=取消 name=\"button\">\r\n            </td>\r\n          </tr>\r\n        </table>\r\n      </td>\r\n    </tr></table>\r\n</body>\r\n</html>\r\n";
?>
