 	$(document).ready(function(){
		if($("#name").text()=='1'){
			$("#name").text("使用中");
		}
		if($("#name").text()=='2'){
			$("#name").text("闲置");
		}
		if($("#name").text()=='3'){
			$("#name").text("维修中");
		}
		if($("#name").text()=='4'){
			$("#name").text("已出租");
		}
		if($("#name").text()=='5'){
			$("#name").text("其它");
		}
		if($("#deprFlag").text()=='y'){
			$("#deprFlag").text("是");
		}
		if($("#deprFlag").text()=='n'){
			$("#deprFlag").text("否");
		}
	})