<?php
echo "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n<link rel=\"stylesheet\" type=\"text/css\" href=\"../../inc/style.css\">\r\n</head>\r\n<script Language=\"JavaScript\">\r\nvar parent_window = parent.dialogArguments;\r\n\r\nfunction click_user(user_id)\r\n{\r\n  TO_VAL=parent_window.form1.";
echo $toid;
echo ".value;\r\n  targetelement=document.all(user_id);\r\n  user_name=targetelement.name;\r\n\r\n  if(TO_VAL.indexOf(\",\"+user_id+\",\")>0 || TO_VAL.indexOf(user_id+\",\")==0)\r\n  {\r\n    if(TO_VAL.indexOf(user_id+\",\")==0)\r\n    {\r\n       parent_window.form1.";
echo $toid;
echo ".value=parent_window.form1.";
echo $toid;
echo ".value.replace(user_id+\",\",\"\");\r\n       parent_window.form1.";
echo $toname;
echo ".value=parent_window.form1.";
echo $toname;
echo ".value.replace(user_name+\",\",\"\");\r\n       borderize_off(targetelement);\r\n    }\r\n    if(TO_VAL.indexOf(\",\"+user_id+\",\")>0)\r\n    {\r\n       parent_window.form1.";
echo $toid;
echo ".value=parent_window.form1.";
echo $toid;
echo ".value.replace(\",\"+user_id+\",\",\",\");\r\n       parent_window.form1.";
echo $toname;
echo ".value=parent_window.form1.";
echo $toname;
echo ".value.replace(\",\"+user_name+\",\",\",\");\r\n       borderize_off(targetelement);\r\n    }\r\n  }\r\n  else\r\n  {\r\n    parent_window.form1.";
echo $toid;
echo ".value+=user_id+\",\";\r\n    parent_window.form1.";
echo $toname;
echo ".value+=user_name+\",\";\r\n    borderize_on(targetelement);\r\n  }\r\n}\r\n\r\nfunction borderize_on(targetelement)\r\n{\r\n color=\"#003FBF\";\r\n targetelement.style.borderColor=\"black\";\r\n targetelement.style.backgroundColor=color;\r\n targetelement.style.color=\"white\";\r\n targetelement.style.fontWeight=\"bold\";\r\n}\r\n\r\nfunction borderize_off(targetelement)\r\n{\r\n  targetelement.style.backgroundColor=\"\";\r\n  targetelement.style.borderColor=\"\";\r\n  targetelement.style.color=\"\";\r\n  targetelement.style.fontWeight=\"\";\r\n}\r\n\r\nfunction begin_set()\r\n{\r\n  TO_VAL=parent_window.form1.";
echo $toid;
echo ".value;\r\n\r\n  for (step_i=0; step_i<document.all.length; step_i++)\r\n  {\r\n    if(document.all(step_i).className==\"menulines\")\r\n    {\r\n       user_id=document.all(step_i).id;\r\n       if(TO_VAL.indexOf(\",\"+user_id+\",\")>0 || TO_VAL.indexOf(user_id+\",\")==0)\r\n          borderize_on(document.all(step_i));\r\n    }\r\n  }\r\n}\r\n\r\nfunction add_all()\r\n{\r\n  TO_VAL=parent_window.form1.";
echo $toid;
echo ".value;\r\n  for (step_i=0; step_i<document.all.length; step_i++)\r\n  {\r\n    if(document.all(step_i).className==\"menulines\")\r\n    {\r\n       user_id=document.all(step_i).id;\r\n       user_name=document.all(step_i).name;\r\n\r\n       if(TO_VAL.indexOf(\",\"+user_id+\",\")<0 && TO_VAL.indexOf(user_id+\",\")!=0)\r\n       {\r\n         parent_window.form1.";
echo $toid;
echo ".value+=user_id+\",\";\r\n         parent_window.form1.";
echo $toname;
echo ".value+=user_name+\",\";\r\n         borderize_on(document.all(step_i));\r\n       }\r\n    }\r\n  }\r\n}\r\n\r\nfunction del_all()\r\n{\r\n  for (step_i=0; step_i<document.all.length; step_i++)\r\n  {\r\n    TO_VAL=parent_window.form1.";
echo $toid;
echo ".value;\r\n    if(document.all(step_i).className==\"menulines\")\r\n    {\r\n       user_id=document.all(step_i).id;\r\n       user_name=document.all(step_i).name;\r\n       if(TO_VAL.indexOf(user_id+\",\")==0)\r\n       {\r\n          parent_window.form1.";
echo $toid;
echo ".value=parent_window.form1.";
echo $toid;
echo ".value.replace(user_id+\",\",\"\");\r\n          parent_window.form1.";
echo $toname;
echo ".value=parent_window.form1.";
echo $toname;
echo ".value.replace(user_name+\",\",\"\");\r\n          borderize_off(document.all(step_i));\r\n       }\r\n       if(TO_VAL.indexOf(\",\"+user_id+\",\")>0)\r\n       {\r\n          parent_window.form1.";
echo $toid;
echo ".value=parent_window.form1.";
echo $toid;
echo ".value.replace(\",\"+user_id+\",\",\",\");\r\n          parent_window.form1.";
echo $toname;
echo ".value=parent_window.form1.";
echo $toname;
echo ".value.replace(\",\"+user_name+\",\",\",\");\r\n          borderize_off(document.all(step_i));\r\n       }\r\n    }\r\n  }\r\n}\r\n\r\nfunction set_user()\r\n{\r\n  URL=\"set_user.php\";\r\n  myleft=(screen.availWidth-600)/2;\r\n  window.open(URL,null,\"height=450,width=600,status=1,toolbar=no,menubar=no,location=no,scrollbars=yes,top=150,left=\"+myleft+\",resizable=yes\");\r\n}\r\n</script>\r\n<body class=\"panel\" topmargin=\"0\" leftmargin=\"0\" onload=\"begin_set()\">\r\n\r\n<table border=\"1\" cellspacing=\"0\" width=\"100%\" class=\"small\" cellpadding=\"3\"  bordercolorlight=\"#000000\" bordercolordark=\"#FFFFFF\">\r\n<tr class=\"TableHeader\">\r\n  <td colspan=\"2\" align=\"center\">公务员</td>\r\n</tr>\r\n<tr class=\"TableContent\">\r\n  <td onclick=\"javascript:add_all();\" style=\"cursor:hand\" align=\"center\" colspan=\"2\">全部添加</td>\r\n</tr>\r\n<tr class=\"TableContent\">\r\n  <td onclick=\"javascript:del_all();\" style=\"cursor:hand\" align=\"center\" colspan=\"2\">全部删除</td>\r\n</tr>\r\n<tr id=\"wxd\" name=\"王秀娣\"  onclick=\"javascript:click_user('wxd')\" class=\"menulines\" style=\"cursor:hand\" align=\"center\">\r\n  <td>OA项目组</td><td>王秀娣</td>\r\n</tr>\r\n<tr id=\"zjk\" name=\"zjk\"  onclick=\"javascript:click_user('zjk')\" class=\"menulines\" style=\"cursor:hand\" align=\"center\">\r\n  <td>财务处</td><td>张家口</td>\r\n</tr>\r\n<tr id=\"zsf\" name=\"钟善峰\"  onclick=\"javascript:click_user('zsf')\" class=\"menulines\" style=\"cursor:hand\" align=\"center\">\r\n  <td>网络处</td><td>钟善峰</td>\r\n</tr>\r\n</table>\r\n</body>\r\n</html>";
?>
