<?php
echo "<html>\r\n<head>\r\n<title></title>\r\n\r\n";
if ( $EDIT_HEIGHT == "" )
{
    $EDIT_HEIGHT = 200;
}
echo "\r\n<!-- Styles -->\r\n<link REL=\"stylesheet\" TYPE=\"text/css\" HREF=\"styles.css\">\r\n\r\n";
echo "<S";
echo "CRIPT>\r\n<!--\r\nvar bLoad=false\t\t\t\t\r\nvar pureText=true\t\t//编辑的内容是纯文本，没有任何格式化信息\r\nvar bodyTag=\"<BODY MONOSPACE STYLE=\\\"font:11pt 宋体\\\">\"\r\nvar bTextMode=false\r\n\r\npublic_description=new Editor\r\n\r\nfunction Editor() {\r\n  this.put_html=SetHtml;\r\n  this.get_html=GetHtml;\r\n}\r\n\r\n//composition是一个Iframe, 用于显示动态编辑的内容。\r\nfunction GetHtml() {\r\n  if (bTextMode)  //如果是文本模式则只取";
echo "内部文本，滤去TAG信息\r\n//不过在这里可以看出来，该文件的大部分代码应是从别的地方 //借用的，其bTextMode与界面上\"查看html源码\"的含义不符\r\n\t           //而且bTextMode实际上根本没有用到\r\n    return Composition.document.body.innerText \r\n  else {\r\n    cleanHtml();    //清理Html中内容，如滤去一些无效的Font标记\r\n    cleanHtml();    //\r\n    return Composition.document.body.innerHTML;   \r\n  }\r\n}\r\n\r\nfunction ";
echo "public_SetMyHtml(sVal) {\r\n  if (bTextMode) \r\n    Composition.document.body.innerText=sVal \r\n  else \r\n    Composition.document.body.innerHTML=sVal\r\n}\r\n\r\nfunction SetHtml(sVal) {\r\n  if (bTextMode) \r\n    Composition.document.body.innerText=sVal \r\n  else \r\n    Composition.document.body.innerHTML=sVal\r\n}\r\n\r\n// -->\r\n</script>\r\n<meta http-equiv=Content-Type content=\"text/html; charset=gb2312\">\r\n";
echo "<s";
echo "tyle type=\"text/css\">\r\n.p2{font-size:9pt;font-family:宋体;color:#000000;line-height:18px;}\r\n.Slink{font-size:9pt;font-family:宋体;color:#333333;line-height:17px;letter-spacing:1px}\r\n\r\n<!--\r\nH3 {\r\n\tfont-family: Arial, Helvetica, Verdana;\r\n\tfont-size: 10pt;\r\n\tfont-weight: bold;\r\n}\r\nH3.real {\r\n\tfont-family: Arial, Helvetica, Verdana;\r\n\tfont-size: 14pt;\r\n\tfont-weight: bold;\r\n}\r\n-->\r\n</STYLE>\r\n</head>\r\n\r\n";
echo "<body onload=\"bLoad=true;if(parent.document.Signature && parent.document.Signature.MText)Composition.document.body.innerHTML = parent.document.Signature.MText.value;\" STYLE=\"margin:0pt;padding:2pt\"  bgcolor=\"#DDDDDD\">\r\n<div class=\"yToolbar\" ID=\"ParaToolbar\">\r\n  <div class=\"TBHandle\"></div>\r\n  ";
echo "<s";
echo "elect ID=\"FontName\" class=\"TBGen\" TITLE=\"字体名\" LANGUAGE=\"javascript\" onchange=\"format('fontname',this[this.selectedIndex].value);\">\r\n    <option class=\"heading\">字体\r\n    <option value=\"宋体\">宋体\r\n    <option value=\"黑体\">黑体\r\n    <option value=\"楷体_GB2312\">楷体\r\n    <option value=\"仿宋_GB2312\">仿宋\r\n    <option value=\"MS Song\">MS宋体\r\n    <option value=\"MS Hei\">MS黑体\r\n    <option value=\"MingLiU\">Mi";
echo "ngLiU\r\n    <option value=\"Arial\">Arial\r\n    <option value=\"Arial Black\">Arial Black\r\n    <option value=\"Arial Narrow\">Arial Narrow\r\n    <option value=\"Bradley Hand ITC\">Bradley Hand ITC\r\n    <option value=\"Brush Script MT\">Brush Script MT\r\n    <option value=\"Century Gothic\">Century Gothic\r\n    <option value=\"Comic Sans MS\">Comic Sans MS\r\n    <option value=\"Courier\">Courier\r\n    <option value=\"Courier New\">";
echo "Courier New\r\n    <option value=\"MS Sans Serif\">MS Sans Serif\r\n    <option value=\"Script\">Script\r\n    <option value=\"System\">System\r\n    <option value=\"Times New Roman\">Times New Roman\r\n    <option value=\"Viner Hand ITC\">Viner Hand ITC\r\n    <option value=\"Verdana\">Verdana\r\n    <option value=\"Wide Latin\">Wide Latin\r\n    <option value=\"Wingdings\">Wingdings\r\n  </select>\r\n  ";
echo "<s";
echo "elect ID=\"FontSize\" class=\"TBGen\" TITLE=\"字号大小\" LANGUAGE=\"javascript\" onchange=\"format('fontsize',this[this.selectedIndex].value);\">\r\n    <option class=\"heading\">字号\r\n    <option value=\"1\">一号\r\n    <option value=\"2\">二号\r\n    <option value=\"3\">三号\r\n    <option value=\"4\">四号\r\n    <option value=\"5\">五号\r\n    <option value=\"6\">六号\r\n    <option value=\"7\">七号\r\n  </select>\r\n  ";
echo "<s";
echo "elect ID=\"ForeColor\" class=\"TBGen\" TITLE=\"字体色彩\" LANGUAGE=\"javascript\" onchange=\"format('forecolor',this[this.selectedIndex].value);\">\r\n    <option class=\"heading\" selected>字色\r\n    <option style=\"COLOR: red\" value=\"red\">红色\r\n    <option style=\"COLOR: blue\" value=\"blue\">蓝色\r\n    <option style=\"COLOR: green\" value=\"green\">绿色\r\n    <option style=\"COLOR: yellow\" value=\"yellow\">黄色\r\n    <option styl";
echo "e=\"COLOR: pink\" value=\"pink\">粉红\r\n    <option style=\"COLOR: cyan\" value=\"cyan\">天青\r\n    <option style=\"COLOR: white\" value=\"white\">白色\r\n    <option style=\"COLOR: darkred\" value=\"darkred\">深红\r\n    <option style=\"COLOR: darkblue value=\"darkblue\">深蓝\r\n    <option style=\"COLOR: darkgreen\" value=\"darkgreen\">深绿\r\n    <option style=\"COLOR: darkyellow\" value=\"darkyellow\">土黄\r\n    <option style=\"COLOR: dar";
echo "kcyan\" value=\"darkcyan\">蓝绿\r\n    <option style=\"COLOR: gray\" value=\"gray\">浅灰\r\n    <option style=\"COLOR: black\" value=\"black\">黑色\r\n  </select>\r\n  ";
echo "<s";
echo "elect ID=\"BackColor\" class=\"TBGen\" TITLE=\"字体背景色彩\" LANGUAGE=\"javascript\" onchange=\"format('backcolor',this[this.selectedIndex].value);\">\r\n    <option class=\"heading\">背景色\r\n    <option style=\"COLOR: red\" value=\"red\">红色\r\n    <option style=\"COLOR: blue\" value=\"blue\">蓝色\r\n    <option style=\"COLOR: green\" value=\"green\">绿色\r\n    <option style=\"COLOR: yellow\" value=\"yellow\">黄色\r\n    <option style=\"";
echo "COLOR: pink\" value=\"pink\">粉红\r\n    <option style=\"COLOR: cyan\" value=\"cyan\">天青\r\n    <option style=\"COLOR: white\" value=\"white\">白色\r\n    <option style=\"COLOR: darkred\" value=\"darkred\">深红\r\n    <option style=\"COLOR: darkblue value=\"darkblue\">深蓝\r\n    <option style=\"COLOR: darkgreen\" value=\"darkgreen\">深绿\r\n    <option style=\"COLOR: darkyellow\" value=\"darkyellow\">土黄\r\n    <option style=\"COLOR: darkcy";
echo "an\" value=\"darkcyan\">蓝绿\r\n    <option style=\"COLOR: gray\" value=\"gray\">浅灰\r\n    <option style=\"COLOR: black\" value=\"black\">黑色\r\n  </select>\r\n <div class=\"TBSep\"></div>\r\n  <div class=\"Btn\" TITLE=\"加粗\" LANGUAGE=\"javascript\" onclick=\"format('bold');\">\r\n    <img class=\"Ico\" src=\"imgs/bold.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"斜体\" LANGUAGE=\"javascript\" onclick=\"format('italic')\">\r\n    <img class=\"Ico\"";
echo " src=\"imgs/italic.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"下划线\" LANGUAGE=\"javascript\" onclick=\"format('underline')\">\r\n    <img class=\"Ico\" src=\"imgs/under.gif\">\r\n  </div>\r\n\r\n</div>\r\n\r\n<div class=\"yToolbar\" ID=\"FormatToolbar\">\r\n  <div class=\"TBHandle\"></div>\r\n  <div class=\"Btn\" TITLE=\"插入超级连接\" LANGUAGE=\"javascript\" onclick=\"createLink()\">\r\n    <img class=\"Ico\" src=\"imgs/wlink.gif\">\r\n  </div>\r\n  <div ";
echo "class=\"Btn\" TITLE=\"剪切\" LANGUAGE=\"javascript\" onclick=\"format('cut')\">\r\n    <img class=\"Ico\" src=\"imgs/cut.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"复制\" LANGUAGE=\"javascript\" onclick=\"format('copy')\">\r\n    <img class=\"Ico\" src=\"imgs/copy.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"粘贴\" LANGUAGE=\"javascript\" onclick=\"format('paste')\">\r\n    <img class=\"Ico\" src=\"imgs/paste.gif\">\r\n  </div>\r\n\r\n  <div class";
echo "=\"TBSep\"></div>\r\n\r\n  <div class=\"Btn\" TITLE=\"左对齐\" NAME=\"Justify\" LANGUAGE=\"javascript\" onclick=\"format('justifyleft')\">\r\n    <img class=\"Ico\" src=\"imgs/aleft.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"居中\" NAME=\"Justify\" LANGUAGE=\"javascript\" onclick=\"format('justifycenter')\">\r\n    <img class=\"Ico\" src=\"imgs/center.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"右对齐\" NAME=\"Justify\" LANGUAGE=\"javascript\"";
echo " onclick=\"format('justifyright')\">\r\n    <img class=\"Ico\" src=\"imgs/aright.gif\">\r\n  </div>\r\n  <div class=\"TBSep\"></div>\r\n  <div class=\"Btn\" TITLE=\"编号\" LANGUAGE=\"javascript\" onclick=\"format('insertorderedlist')\">\r\n    <img class=\"Ico\" src=\"imgs/nlist.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"项目符号\" LANGUAGE=\"javascript\" onclick=\"format('insertunorderedlist')\">\r\n    <img class=\"Ico\" src=\"imgs/blist.gif\"";
echo ">\r\n  </div>\r\n  <div class=\"TBSep\"></div>\r\n  <div class=\"Btn\" TITLE=\"减少缩进量\" LANGUAGE=\"javascript\" onclick=\"format('outdent')\">\r\n    <img class=\"Ico\" src=\"imgs/ileft.gif\">\r\n  </div>\r\n  <div class=\"Btn\" TITLE=\"增加缩进量\" LANGUAGE=\"javascript\" onclick=\"format('indent')\">\r\n    <img class=\"Ico\" src=\"imgs/iright.gif\" >\r\n  </div>\r\n  <div ID=\"EditMode\" class=\"TBGen\" style=\"width:150\" TITLE=\"编辑模式\">\r\n    <inp";
echo "ut type=checkbox name=\"switchMode\" LANGUAGE=\"javascript\" onclick=\"setMode(switchMode.checked)\">        \r\n编辑HTML源文件\r\n  </div>\r\n</div>\r\n\r\n<IFRAME class=\"Composition\" width=\"100%\" ID=\"Composition\" height=\"";
echo $EDIT_HEIGHT;
echo "\">\r\n</IFRAME>\r\n\r\n";
echo "<S";
echo "CRIPT>\r\n<!--\r\nComposition.document.open();\r\nComposition.document.write(bodyTag);\r\nComposition.document.close();\r\nComposition.document.designMode=\"On\";\r\nComposition.focus();\r\nsetTimeout(\"Composition.focus()\",0)\r\n// -->\r\n</SCRIPT>\r\n\r\n";
echo "<s";
echo "cript LANGUAGE=\"Javascript\" SRC=\"compose.js\">\r\n</script>\r\n\r\n</body>\r\n</html>\r\n";
?>
